//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presenter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Presenter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16:9.
        /// </summary>
        internal static string defaultAspectRatio {
            get {
                return ResourceManager.GetString("defaultAspectRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://get.videolan.org/vlc/2.1.5/win32/vlc-2.1.5-win32.exe.
        /// </summary>
        internal static string downloadVlcUrl {
            get {
                return ResourceManager.GetString("downloadVlcUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4000.
        /// </summary>
        internal static string hideControlTimer {
            get {
                return ResourceManager.GetString("hideControlTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40000.
        /// </summary>
        internal static string lostGoodRtspOnStartTimer {
            get {
                return ResourceManager.GetString("lostGoodRtspOnStartTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7000.
        /// </summary>
        internal static string lostGoodRtspTimer {
            get {
                return ResourceManager.GetString("lostGoodRtspTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30000.
        /// </summary>
        internal static string lostRtspOnStartTimer {
            get {
                return ResourceManager.GetString("lostRtspOnStartTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5000.
        /// </summary>
        internal static string lostRtspTimer {
            get {
                return ResourceManager.GetString("lostRtspTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32.
        /// </summary>
        internal static string matrixMaxX {
            get {
                return ResourceManager.GetString("matrixMaxX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32.
        /// </summary>
        internal static string matrixMaxY {
            get {
                return ResourceManager.GetString("matrixMaxY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.xml.
        /// </summary>
        internal static string settingsFileName {
            get {
                return ResourceManager.GetString("settingsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3000.
        /// </summary>
        internal static string showHintTimer {
            get {
                return ResourceManager.GetString("showHintTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30000.
        /// </summary>
        internal static string stopBadRtspTimer {
            get {
                return ResourceManager.GetString("stopBadRtspTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60000.
        /// </summary>
        internal static string stopGoodRtspTimer {
            get {
                return ResourceManager.GetString("stopGoodRtspTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 120000.
        /// </summary>
        internal static string stopOnInvisibleTimer {
            get {
                return ResourceManager.GetString("stopOnInvisibleTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20000.
        /// </summary>
        internal static string switchToBadRtspTimer {
            get {
                return ResourceManager.GetString("switchToBadRtspTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 110.
        /// </summary>
        internal static string switchToGoodRtspPercent {
            get {
                return ResourceManager.GetString("switchToGoodRtspPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4000.
        /// </summary>
        internal static string switchToGoodRtspTimer {
            get {
                return ResourceManager.GetString("switchToGoodRtspTimer", resourceCulture);
            }
        }
    }
}
